-- 1. 创建EMP_Info表。
CREATE TABLE EMP_INFO (
	EMPNO INT PRIMARY KEY,
	ENAME VARCHAR(20),
	DEPTNO NUMERIC(2, 0)
);

-- 2. 在EMP_Info表中定义一个外码DEPTNO，其被参照表是DEPT表。
ALTER TABLE EMP_INFO
ADD CONSTRAINT FK_EMP_INFO_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);

-- 3. 创建Prod_Info表。
CREATE TABLE PROD_INFO (
	PRODUCTNO CHAR(5) PRIMARY KEY,
	PNAME VARCHAR(20),
	COLOR VARCHAR(10) CONSTRAINT CK_COLOR CHECK (COLOR IN ('Red', 'Blue', 'Green'))
);

-- 4. 从Prod_Info表中删除对颜色字段的约束，然后再将约束添加回去。
ALTER TABLE PROD_INFO
DROP CONSTRAINT CK_COLOR;

ALTER TABLE PROD_INFO
ADD CONSTRAINT CK_COLOR CHECK (COLOR IN ('Red', 'Blue', 'Green'));

-- 5. 创建Supplier表。
CREATE TABLE SUPPLIER (SUPPLIERNO CHAR(5) PRIMARY KEY, SNAME VARCHAR(20));

-- 6. 创建SP表
CREATE TABLE SP (SUPPLIERNO CHAR(5), PRODUCTNO CHAR(5));

-- 7. 在SP表中定义一个外码ProductNO，其被参照表是Prod_Info表；定义另一个外码SupplierNO，其被参照表是Supplier表。
ALTER TABLE SP
ADD CONSTRAINT FK_SP_PRODUCTNO FOREIGN KEY (PRODUCTNO) REFERENCES PROD_INFO (PRODUCTNO);

ALTER TABLE SP
ADD CONSTRAINT FK_SP_SUPPLIERNO FOREIGN KEY (SUPPLIERNO) REFERENCES SUPPLIER (SUPPLIERNO);

-- 8. 给SP表添加PRICE（采购价格）属性列，数据类型为数值型，宽度为5，小数位数为2。
ALTER TABLE SP
ADD COLUMN PRICE NUMERIC(5, 2);

-- 9. 给SP表的PRICE属性添加一个约束，规定采购价格必须大于0。
ALTER TABLE SP
ADD CONSTRAINT CK_PRICE CHECK (PRICE > 0);

-- 10. 将SP表中PRICE属性的宽度增加到6位，小数位数不变。
ALTER TABLE SP
ALTER COLUMN PRICE TYPE NUMERIC(6, 2);

-- 11. 从SP表中将PRICE属性删除。
ALTER TABLE SP
DROP COLUMN PRICE;